name: invsr
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asttokens==3.0.0
      - bitsandbytes==0.45.5
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - facexlib==0.3.0
      - fastapi==0.115.12
      - ffmpy==0.5.0
      - filelock==3.13.1
      - filterpy==1.4.5
      - fonttools==4.57.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - future==1.0.0
      - gradio==5.8.0
      - gradio-client==1.5.1
      - grpcio==1.71.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - icecream==2.1.4
      - idna==3.10
      - imageio==2.37.0
      - imgaug==0.4.0
      - importlib-metadata==8.6.1
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - loguru==0.7.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.3
      - numba==0.61.2
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - orjson==3.10.16
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.0.0
      - protobuf==6.30.2
      - psutil==7.0.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pyiqa==0.1.12
      - pyparsing==3.2.3
      - python-box==7.3.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - ruff==0.11.7
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scipy==1.15.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shapely==2.1.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tifffile==2025.3.30
      - timm==1.0.15
      - tokenizers==0.15.2
      - tomli==2.2.1
      - tomlkit==0.13.2
      - tqdm==4.67.1
      - transformers==4.37.2
      - triton==3.0.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - wcwidth==0.2.13
      - websockets==14.2
      - werkzeug==3.1.3
      - xformers==0.0.27.post2
      - yapf==0.43.0
      - zipp==3.21.0

