name: gemini
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.0.4
      - decorator==5.2.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.18.0
      - flask==3.0.3
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - google-auth==2.39.0
      - google-genai==1.13.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - ipython==8.36.0
      - ipywidgets==8.1.6
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.0
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - narwhals==1.37.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - plotly==6.0.1
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.24.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - supervision==0.25.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.3.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - zipp==3.21.0

