name: match
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.4.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - black==25.1.0
      - blinker==1.9.0
      - cachetools==5.5.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - coacd==1.0.5
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclasses-json==0.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.3.9
      - docstring-parser==0.16
      - easydict==1.13
      - einops==0.8.1
      - etils==1.12.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.8
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.17.0
      - flask==3.0.3
      - flatbuffers==25.2.10
      - flow-vis==0.1
      - fonttools==4.56.0
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - future==1.0.0
      - gdown==5.2.0
      - genesis-world==0.2.1
      - glfw==2.8.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.1
      - google-api-python-client==2.161.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-cloud-aiplatform==1.71.1
      - google-cloud-bigquery==3.29.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.14.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-generativeai==0.8.4
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.67.0
      - gradio==5.4.0
      - gradio-client==1.4.2
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.70.0
      - grpcio-status==1.70.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - ipython==8.32.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - kornia==0.6.11
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - libigl==2.5.1
      - lightning-utilities==0.12.0
      - llvmlite==0.44.0
      - loguru==0.5.3
      - lxml==5.3.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - moviepy==2.1.2
      - mpmath==1.3.0
      - mujoco==3.2.5
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.26.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnxruntime==1.20.1
      - open3d==0.19.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - openexr==3.3.2
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==25.0.1
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pooch==1.8.2
      - portalocker==3.1.1
      - poselib==2.0.4
      - proglog==0.1.10
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycollada==0.9
      - pycolmap==0.6.1
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydeprecate==0.3.1
      - pydub==0.25.1
      - pygel3d==0.5.2
      - pyglet==2.1.2
      - pygltflib==1.16.0
      - pygments==2.19.1
      - pymeshlab==2023.12.post2
      - pynvml==12.0.0
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.12
      - pytlsd==0.0.2
      - pytorch-lightning==1.4.9
      - pytz==2025.1
      - pyvista==0.44.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - ruff==0.9.6
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-image==0.25.1
      - scikit-learn==1.6.1
      - scipy==1.11.2
      - scooby==0.10.0
      - screeninfo==0.8.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - spaces==0.32.0
      - stack-data==0.6.3
      - starlette==0.45.3
      - supervision==0.25.1
      - sympy==1.13.1
      - taichi==1.7.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.1
      - tetgen==0.6.4
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - tokenizers==0.21.0
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.6.0
      - torchmetrics==1.6.1
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.49.0
      - transforms3d==0.4.2
      - trimesh==4.6.2
      - triton==3.2.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - vertexai==1.71.1
      - vtk==9.3.1
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - yacs==0.1.8
      - yarl==1.18.3
      - zipp==3.21.0
