
WidowX:
  name: "WidowX"
  path: "./utils/assets/descriptions/widowx_description/wx250s.urdf"
  ee_link: "ee_gripper_link"
  pc_idxs: 4
  position:
    x: 0.0
    y: 0.0
    z: 1.0
  quaternion:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

franka:
  name: "franka"
  path: "./utils/assets/franka_fr3_sf85/model.xml"
  ee_link: "panda_hand"
  pc_idxs: 4
  # pc_idxs: [1]
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  quaternion:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

ur5:
  name: "ur5"
  path: "./utils/assets/ur5e/urdf/ur5e.urdf"
  ee_link: "ee_virtual_link"
  pc_idxs: 4
  # pc_idxs: [1]
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  quaternion:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0